### ISSUE TITLE
Mouse pointer artifacts after update to displaylink 4.4.24 

### ISSUE THREAD

**Issue by cacarr-pdxweb** [DisplayLink/evdi#144]
Trailing pointers and multiple pointers persisting, particularly on the DisplayLink monitor. Also, graphical glitches occur where hovering. This started after 4.4.24 (along with no longer being able to achieve rotation/portrait orientation, but that's another issue).

kernel 4.19.4
Arch - on both Gnome and Deepin desktops

**Comment by skriems** [comment]
I can confirm this issue on i3. Will check Gnome tomorrow

specs:
kernel: 4.19.8-arch1-1-ARCH
xorg-server: 1.20.3
evdi: 1.5.1
displaylink: 4.4.24

**Comment by skriems** [comment]
That solved itself for me with the current kernel 4.20.arch1 on i3

**Comment by displaylink-dkurek** [comment]
Closing (as @skriems says it has been solved by kernel upgrade and no one opposites)

**Comment by mrTsjolder** [comment]
The issue seems to be there again for kernel version 5.2.9 --- I updated my arch linux from 5.2.5 to 5.2.9 and experienced the same (or at least similar) graphical glitches. I'm using Gnome and reverting back to 5.2.5 resolved the glitches.

@displaylink-dkurek Any insights on why this might be happening

**Comment by runningnak3d** [comment]
@mrTsjolder I just did a fresh install of Arch, and downgrading to 5.2.5 didn't solve it for me. Do you mind posting the version of Xorg you are running?

**Comment by mrTsjolder** [comment]
@runningnak3d Xorg server is at 1.20.5-2

**Comment by mrTsjolder** [comment]
@runningnak3d I just tried to update my system again, which reintroduced the problem. This time, downgrading vulkan-intel to 19.1.4-1 and vulkan-icd-loader to 1.1.119-1 resolved the glitches. I am not sure whether it is necessary/makes sense to downgrade both, but that's what I did and I'm sticking with it for now...
