### ISSUE TITLE
Choppy image on Ubuntu 18.04 & 19.04 with Ryzen 2500U processor

### ISSUE THREAD

**Issue by nicoco007** [DisplayLink/evdi#164]
I'm not sure if this is an EVDI or a DisplayLinkManager issue, but since playing around with kernel versions helped I'm guessing it's EVDI &ndash; I'm sorry if it isn't.

I got a new laptop with a Ryzen 2500U processor (Vega 8 graphics) a few months ago and have been struggling to get DisplayLink to work properly on Ubuntu; whatever I try, the image is always choppy.

I've tried clean installs of Ubuntu 18.04 (with official 4.15 and mainline 4.18 kernels) and 19.04 (with mainline 4.18, 4.19, 4.20, 5.0, and 5.1 kernels) with the latest version (1.6.1) of EVDI and the one that comes with the latest version of the driver (1.6.0) to no avail. I've also tried putting various configurations in `/etc/X11/xorg.conf.d/20-displaylink.conf` (I unfortunately did not write them down while going through them) but the ones I used didn't help either. On version 4 kernels, the image is mostly choppy when large changes to the image are being made (e.g. when moving a window, the movement is choppy and the image tears multiple times) with small stutters happening once in a while on both the main screen and the DisplayLink display, while on version 5 kernels the image stuttered even with just the cursor moving, as if it were running at a very low framerate. Also, if only the external monitor is used to display an image (i.e. laptop screen is disabled), stuttering and input lag skyrocket. CPU usage doesn't look abnormal with the external screen plugged in and everything works fine when it's not. Everything works normally on Windows.

Below is a still image of the problem and [here's a video of what it looks like](https://youtu.be/hyro8sF4qTU) (this is on Kubuntu 19.04 running kernel version 4.18.20 and DisplayLink 5.1.26 with EVDI 1.6.0, but the exact same symptoms are exhibited by Ubuntu 18.04).
![image](https://user-images.githubusercontent.com/1349975/60145514-4760f000-9794-11e9-8509-a9dca3019135.png)

I'm not sure where to find logs so I used the DLSupportTool and it gave me this: [DLSupportTool_Output_2019-06-25T20_04_17.429732.zip](https://github.com/DisplayLink/evdi/files/3327680/DLSupportTool_Output_2019-06-25T20_04_17.429732.zip)

Any ideas?

**Comment by nicoco007** [comment]
@Crashdummyy over on AdnanHodzic/displaylink-debian#265 found out that running with Wayland rather than Xorg makes the problem essentially disappear completely. I can confirm that this works on my end too with a clean full install of Ubuntu 19.04.

**Comment by displaylink-dkurek** [comment]
Hi @nicoco007 
Does this laptop have two GPUs? (if so) I know it is not actual solution but you could try to disable
one in BIOS and check again. For now this is the only thing that comes to my mind for a 'quick' fix.

**Comment by Crashdummyy** [comment]
> Hi @nicoco007
> Does this laptop have two GPUs? (if so) I know it is not actual a solution but you could try to disable
> one in BIOS and check again. For now this is the only thing that comes to my mind for a 'quick' fix (if everything else is not working).

He uses an Vega 8 if I am not mistaken.
So there is no dedicated GPU present.

Disabling one GPU in the Bios doesn't fix these Problems for my other laptop ( using the graphics Unit of the i7-4710HQ )

**Comment by nicoco007** [comment]
I can confirm that my laptop does not have a dedicated GPU and only uses the integrated Vega 8 graphics.

**Comment by PierrickBrun** [comment]
Hi, I'm reporting the same problem with the same CPU/GPU. I use OpenSUSE Tumbleweed though (kernel 5.1.16)

**Comment by ChESch** [comment]
Can confirm the same problem with an AMD Ryzen 7 PRO 3700U in my new ThinkPad 495s running Kubuntu 19.04

**Comment by jacobchurch** [comment]
Prior to kernel 5.0.0-23-generic, I was getting 1fps from glxgears with my 2500U HP 17z-ca000 cto laptop and Dell D3100 dock. After updating my kernel today, I am getting about 45-58fps with the DisplayLinkManager process running at 200% cpu (and about 100% without glxgears running)
evdi version: 1.6.1 20180913
DisplayLink driver version: 5.2 (7/8/19)
OS: kubuntu 19.04
Never made a note of the previous kernel version I was using when getting 1fps

I've also tried the pro driver in the past following [this youtube guide](https://www.youtube.com/watch?v=97fj4bGJxVM&feature=youtu.be). The performance seemed ok, but the screen tearing (is that what that diagonal line is called?) drove me crazy.

Happy to help investigate and report back if someone can point me in the right direction.

**Comment by nicoco007** [comment]
@jacobchurch Yeah, that's roughly what I'm getting too. I just tried again with kernel 5.2.11 (latest as of writing this) and driver version 5.2 with the same results as earlier. Any updates/ideas on this @displaylink-dkurek ?

**Comment by hosler** [comment]
im experiencing this issue on an hp envy x360 15z

**Comment by Johnnyreyman** [comment]
I am also experiencing this issue on Linux Mint 19.1 with an AMD A6-5200 APU with Radeon™ HD Graphics. My screen tares.

**Comment by kvaps** [comment]
Hi, I have the same problem on xorg:

* **OS:** Arch Linux x86_64 
* **Host:** Lenovo ideapad 720S-13ARR 
* **Kernel:** 5.3.10-arch1-1 
* **CPU:** AMD Ryzen 7 2700U
* **GPU:** AMD Radeon RX Vega 10

more details about my installation: https://github.com/DisplayLink/evdi/issues/171

I've tried to install gdm on wayland, and can confirm that displaylink is working fine on it.
Unfortunately I can't use gdm for my purpose, I need working X instead.

**Comment by nicoco007** [comment]
I just installed the amdgpu-pro driver on my laptop as @kvaps did and can confirm that also fixes the issue on my end. I however am running an Ubuntu-based distro so I ended up using [this version of the amdgpu-pro driver from AMD's website](https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux), [the script attached to this message](https://bugs.freedesktop.org/show_bug.cgi?id=110795#c29) (comment 29 by Andrew Shark), and [the displaylink-debian script](https://github.com/AdnanHodzic/displaylink-debian) (after running, I also had to delete the `/usr/share/X11/xorg.conf.d/20-displaylink.conf` file to get the screens to be detected properly). This got everything working on Kubuntu 19.04 with X11 and kernel version 5.0.0-36-generic (the one that comes with it by default as of writing this). I'm not sure what FPS it's running at, but at least it's usable now.

**Comment by displaylink-dkurek** [comment]
Closing as the original issue was handled.

**Comment by ChESch** [comment]
Hello, how was this problem solved now? Is installing the proprietary driver really the only solution?

**Comment by displaylink-dkurek** [comment]
Not solved, handled.
If EVDI + amdgpu-pro work OK then it might we worth checking what is 
happening in the open source equivalent of the AMD proprietary driver.

**Comment by kvaps** [comment]
I can append that after installing [`amd-ucode`](https://wiki.archlinux.org/index.php/Microcode) it is started working even better. Now even 4K video from youtube is showing without glitches 🎉

**Comment by haeggee** [comment]
Any updates on this? I am also using the Ryzen 7 with Radeon RX Vega 10, and the workaround to install the proprietary drivers does not work since the AUR package is currently out of date. Any help would be much appreciated, since I experience the exact same problem described above.

**Comment by ChESch** [comment]
@haeggee I have an AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx and I cannot report any success either. I tried freshly installing Ubuntu 18.04.4 on my Thinkpad T495s, installed the official displaylink-driver, choppy image, tried installing amdgpu-pro, still choppy image. I don't think that the solution is to install the amdgpu-pro driver. Funny thing is, people in this issue report that it should be much better with wayland, while the displaylink website states that only x-org is supported...

**Comment by Crashdummyy** [comment]
I got it to work with the amdgpu driver.
It works almost flawlessly ( sometimes a little tearing ).

- Insttaled [amdgpupro 19.30](https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-19-30-unified)
- Installed the DisplaylinkDrivers [from here](https://github.com/AdnanHodzic/displaylink-debian)

However this script failed on compiling EVDI on my machine with some Error for missing headers ( which I had installed ).
I had previsouly installed the official displaylink driver ( with stuttering issues and low resolution ).
displaylink is now using the bundled evdi ( v 1.6.1 )

**Comment by ChESch** [comment]
@Crashdummyy What Linux-Distro and version are you using?

**Comment by Crashdummyy** [comment]
> @Crashdummyy What Linux-Distro and version are you using?

```sh
Distributor ID:	Ubuntu
Release:	19.10
Description:	Ubuntu 19.10
Codename:	eoan
Kernel Version: 5.3.0-42-generic
Processor Type: x86_64
```

**Comment by ChESch** [comment]
@Crashdummyy So how did you install the amdgpu-pro driver on 19.10, when the driver is only available for 18.04?

**Comment by Crashdummyy** [comment]
@ChESch
Has been a while but I remember it being kinda hacky to install.
There is a script [over here](https://gist.github.com/tuxutku/79daa2edca131c1525a136b650cdbe0a) maybe that will make the process easier for you.

**Comment by ChESch** [comment]
@Crashdummyy Okay thank you, I will take a look at it

**Comment by ChESch** [comment]
@Crashdummyy I tried the script, still same result, laggy as shit... I think at this point I will just forget about working displaylink...

**Comment by Crashdummyy** [comment]
@ChESch Sorry I can't help you any further.
I reinstalled Ubuntu 19.10 yesterday with amdgpu for 19.30 ( still got the files ).

I am using these Dockings:
[With PowerDelivery](https://i-tec.cz/en/produkt/catriple4kdockpd-2/)
[Without](https://i-tec.cz/en/produkt/cadual4kdock-2/)

I use two external Displays: 2560x1440@144Hz
Both completely Tearfree with the official Displaylink driver.
( Kernel now on 5.3.0-45-generic )

**Comment by ChESch** [comment]
@Crashdummyy Well I am using exactly the same Dock and also the latest Kernel from 19.10.
Could you please post your exact steps to install the amdgpu-pro drivers as well as the output from `inxi -G` Thanks!

**Comment by Crashdummyy** [comment]
@ChESch 
You could check [their gitlab](https://gitlab.freedesktop.org/drm/amd/-/issues/26)
or even [youtube](https://www.youtube.com/watch?v=97fj4bGJxVM)

My installation steps at that time were:
- Download [official driver](https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-19-30-unified)
- removed ubuntu version hardcoding
- install displaylink and dependencies ( like dkms )
- run script
- remove amdgpu-pro from sources to prevent it from reinstall every time ( don't know why it does that on every upgrade... didn't care )

```sh
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.5 driver: amdgpu resolution: 2560x1440~144Hz, 2560x1440~144Hz 
           OpenGL: renderer: AMD Radeon Graphics v: 4.6.13572 Core Profile Context 

```

**Comment by ChESch** [comment]
@Crashdummyy So how did you remove the Version hardcoding?

**Comment by ChESch** [comment]
@Crashdummyy Sorry, just realised you used the 19.30 driver... the 19.50 seems to have another version hardcoding which is not handled at the script shown at their gitlab, I already tried to modify that, but I didn't have any success

**Comment by Crashdummyy** [comment]
Could be that 19.50 is failing.
I installed 19.30 as there didn't exist a 19.50 ( or maybe I just didn't found it last year )

You can find out how to delete the checks on the youtube/gitlab site.
There were some references inside the amdgpu-core pacakge

I also did 
```
# not sure if 'no-dkms' but --help will help ;)
$ amdgpu-pro-install --no-dkms
```

**Comment by ChESch** [comment]
I tried it again, same result. When amdgpu-pro installs, after reboot I just get an black screen and have to do an CTRL+ALT+F2 and `apt purge amdgpu-pro-*` in order to get KDE up again.

**Comment by virajs94** [comment]
This issue is effecting me as well using Ubuntu 18.04.4, kernel 5.3, and a Radeon RX 570 GPU (no integrated GPU). Previously had it working perfectly with the amdgpu-pro driver, but when I turned on the computer this morning I was met with hanging blank purple screens on both monitors which might be an indicator of a library update somewhere. Not sure though. Does anyone have any luck with this with a RX 500-series GPU? Really regretting not documenting my steps in getting it to work right now...

**Comment by kvaps** [comment]
> When amdgpu-pro installs, after reboot I just get an black screen and have to do an CTRL+ALT+F2 and apt purge amdgpu-pro-* in order to get KDE up again.

@ChESch this is known problem of proprietary amdgpu driver:
https://wiki.archlinux.org/title/AMDGPU_PRO#Workaround_for_using_proprietary_OpenGL

There is only option to use <20.00 version of driver 🙁

**Comment by kvaps** [comment]
Ah, I just found that [patch](https://github.com/pioto1225/evdi/tree/amd_vmap_texture ) by @pioto1225 and option `vmap_texture=1` is actually works fine on my Lenovo ideapad 720S-13ARR.

I prepared [AUR package](https://aur.archlinux.org/packages/evdi-amd-vmap-texture/) with the change for myself.
