### ISSUE TITLE
Kernel traces on 4.4 with Fedora

### ISSUE THREAD

**Issue by wpoely86** [DisplayLink/evdi#20]
On Fedora 23 with kernel 4.4.7-300.fc23.x86_64, I'm getting a lot of kernel traces but everything seems to work fine. 
This is on a MacBook Pro with Intel Iris 6100 gpu connected to a Dell D3100 hub.

An example of such a trace (they are all the same).
```
[26434.567965] ------------[ cut here ]------------
[26434.567975] WARNING: CPU: 0 PID: 1715 at include/drm/drm_gem.h:146 evdi_fb_user_fb_create+0x190/0x1a0 [evdi]()
[26434.567977] Modules linked in: lp parport cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_nat ebtable_broute bridge stp llc ebtables ip6table_raw ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_security ip6table_mangle ip6table_filter ip6_tables iptable_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_security iptable_mangle bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel joydev iTCO_wdt iTCO_vendor_support kvm snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_codec_hdmi btusb nls_utf8 btrtl btbcm btintel snd_hda_intel hfsplus bluetooth irqbypass
[26434.568014]  crct10dif_pclmul snd_hda_codec crc32_pclmul crc32c_intel brcmfmac snd_hda_core brcmutil snd_hwdep cfg80211 snd_seq snd_seq_device snd_pcm mmc_core bcm5974 thunderbolt snd_timer rfkill snd i2c_i801 intel_pch_thermal lpc_ich mei_me soundcore mei shpchp acpi_als sbs tpm_tis kfifo_buf sbshc industrialio spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[26434.568036] CPU: 0 PID: 1715 Comm: Xorg Tainted: G        W  OE   4.4.7-300.fc23.x86_64 #1
[26434.568037] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[26434.568039]  0000000000000286 00000000d3af2335 ffff880241fa3bf8 ffffffff813b5f8e
[26434.568041]  0000000000000000 ffffffffa07a1a0c ffff880241fa3c30 ffffffff810a4122
[26434.568042]  ffff8801caeb7400 ffff88006d0a9000 ffff880241fa3d18 ffff88013e0e0b40
[26434.568044] Call Trace:
[26434.568049]  [<ffffffff813b5f8e>] dump_stack+0x63/0x85
[26434.568052]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[26434.568053]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[26434.568056]  [<ffffffffa079eca0>] evdi_fb_user_fb_create+0x190/0x1a0 [evdi]
[26434.568066]  [<ffffffffa0046220>] internal_framebuffer_create+0x830/0x960 [drm]
[26434.568074]  [<ffffffffa004b0ad>] drm_mode_addfb2+0x2d/0xa0 [drm]
[26434.568081]  [<ffffffffa004b19c>] drm_mode_addfb+0x7c/0xb0 [drm]
[26434.568087]  [<ffffffffa003c602>] drm_ioctl+0x152/0x540 [drm]
[26434.568094]  [<ffffffffa004b120>] ? drm_mode_addfb2+0xa0/0xa0 [drm]
[26434.568097]  [<ffffffff813407fc>] ? selinux_file_ioctl+0x10c/0x1c0
[26434.568100]  [<ffffffff81241428>] do_vfs_ioctl+0x298/0x480
[26434.568102]  [<ffffffff813380b3>] ? security_file_ioctl+0x43/0x60
[26434.568104]  [<ffffffff81241689>] SyS_ioctl+0x79/0x90
[26434.568107]  [<ffffffff817a10ee>] entry_SYSCALL_64_fastpath+0x12/0x71
[26434.568108] ---[ end trace 02c5e33a8eb8360e ]---
```

**Comment by wpoely86** [comment]
I've tried running 0a496210b8311006d950f9b9fd382c8c2327cbc7 on this system but that didn't detect any displays.

**Comment by wpoely86** [comment]
I've tried it again with v1.1.61 release on kernel 4.4.8-300.fc23.x86_64 and I got:
```
[    5.733283] evdi: module verification failed: signature and/or required key missing - tainting kernel
[    5.735626] evdi: [I] Initialising logging on level 5
[   89.853715] evdi: [D] add_store:195 Increasing device count to 1
[   89.854285] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[   89.854836] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exist!
[   89.854840] evdi: [D] evdi_detect:72 Painter is disconnected
[   89.854844] evdi evdi.0: No connectors reported connected with modes
[   89.854846] [drm] Cannot find any crtc or sizes - going 1024x768
[   89.856856] evdi evdi.0: fb1: evdidrmfb frame buffer device
[   89.856860] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   89.856861] [drm] No driver support for vblank timestamp query.
[   89.856863] [drm] evdi: evdi_stats_init
[   89.856867] [drm] Initialized evdi 1.1.61 20160510 on minor 1
[   89.864510] ------------[ cut here ]------------
[   89.864520] WARNING: CPU: 3 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   89.864522] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   89.864563]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   89.864598] CPU: 3 PID: 1700 Comm: Xorg Tainted: G           OE   4.4.8-300.fc23.x86_64 #1
[   89.864600] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   89.864602]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   89.864605]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   89.864608]  0000000000000000 ffff8802636fbde8 ffff88022bec4f00 0000000000000072
[   89.864611] Call Trace:
[   89.864618]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   89.864623]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   89.864626]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   89.864630]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   89.864647]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   89.864659]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   89.864671]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   89.864676]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   89.864680]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   89.864684]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   89.864687]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   89.864691]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   89.864693] ---[ end trace 684b75046f045d09 ]---
[   89.892973] evdi: [D] evdi_detect:72 Painter is disconnected
[   89.893616] evdi: [D] evdi_detect:72 Painter is disconnected
[   89.898403] ------------[ cut here ]------------
[   89.898413] WARNING: CPU: 3 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   89.898414] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   89.898454]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   89.898488] CPU: 3 PID: 1700 Comm: Xorg Tainted: G        W  OE   4.4.8-300.fc23.x86_64 #1
[   89.898490] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   89.898492]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   89.898496]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   89.898498]  0000000000000000 ffff8802636fbde8 ffff88025b358100 0000000000000072
[   89.898502] Call Trace:
[   89.898508]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   89.898512]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   89.898514]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   89.898518]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   89.898535]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   89.898545]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   89.898557]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   89.898563]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   89.898566]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   89.898569]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   89.898572]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   89.898575]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   89.898577] ---[ end trace 684b75046f045d0a ]---
[   89.898590] ------------[ cut here ]------------
[   89.898595] WARNING: CPU: 3 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   89.898595] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   89.898627]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   89.898654] CPU: 3 PID: 1700 Comm: Xorg Tainted: G        W  OE   4.4.8-300.fc23.x86_64 #1
[   89.898656] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   89.898657]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   89.898660]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   89.898663]  0000000000000000 ffff8802636fbde8 ffff88025b358800 0000000000000072
[   89.898666] Call Trace:
[   89.898669]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   89.898672]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   89.898674]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   89.898678]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   89.898689]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   89.898699]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   89.898709]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   89.898713]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   89.898716]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   89.898719]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   89.898722]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   89.898725]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   89.898726] ---[ end trace 684b75046f045d0b ]---
[   89.902086] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   89.902090] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   89.902112] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   89.902113] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   89.913428] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff8802627b7600 tries to close us
[   89.913431] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   89.930578] evdi: [E] evdi_painter_connect:405 Edid length too large
[   90.368283] evdi: [D] add_store:195 Increasing device count to 2
[   90.368935] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[   90.369321] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exist!
[   90.369324] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.369330] evdi evdi.1: No connectors reported connected with modes
[   90.369333] [drm] Cannot find any crtc or sizes - going 1024x768
[   90.372490] evdi evdi.1: fb2: evdidrmfb frame buffer device
[   90.372495] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   90.372496] [drm] No driver support for vblank timestamp query.
[   90.372498] [drm] evdi: evdi_stats_init
[   90.372504] [drm] Initialized evdi 1.1.61 20160510 on minor 2
[   90.378635] ------------[ cut here ]------------
[   90.378645] WARNING: CPU: 1 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   90.378646] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   90.378680]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   90.378710] CPU: 1 PID: 1700 Comm: Xorg Tainted: G        W  OE   4.4.8-300.fc23.x86_64 #1
[   90.378711] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   90.378713]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   90.378716]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   90.378718]  0000000000000000 ffff8802636fbde8 ffff88008a121e00 0000000000000072
[   90.378721] Call Trace:
[   90.378727]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   90.378730]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   90.378732]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   90.378735]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   90.378749]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   90.378759]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   90.378769]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   90.378773]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   90.378776]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   90.378779]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   90.378782]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   90.378785]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   90.378787] ---[ end trace 684b75046f045d0c ]---
[   90.385099] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.385155] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.385490] ------------[ cut here ]------------
[   90.385497] WARNING: CPU: 1 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   90.385498] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   90.385533]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   90.385562] CPU: 1 PID: 1700 Comm: Xorg Tainted: G        W  OE   4.4.8-300.fc23.x86_64 #1
[   90.385563] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   90.385565]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   90.385568]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   90.385570]  0000000000000000 ffff8802636fbde8 ffff88025a530300 0000000000000072
[   90.385572] Call Trace:
[   90.385578]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   90.385581]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   90.385583]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   90.385586]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   90.385602]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   90.385611]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   90.385621]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   90.385625]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   90.385629]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   90.385632]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   90.385635]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   90.385637]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   90.385639] ---[ end trace 684b75046f045d0d ]---
[   90.385680] ------------[ cut here ]------------
[   90.385684] WARNING: CPU: 1 PID: 1700 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   90.385685] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm usbnet snd_usbmidi_lib mii snd_rawmidi rfcomm fuse evdi(OE) nf_conntrack_netbios_ns nf_conntrack_broadcast ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_broute bridge stp llc ebtable_nat ebtable_filter ebtables ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_raw ip6table_filter ip6_tables iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_raw bnep intel_rapl iosf_mbi x86_pkg_temp_thermal kvm_intel kvm nls_utf8 iTCO_wdt hfsplus iTCO_vendor_support joydev irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel snd_hda_codec_hdmi snd_hda_codec_cirrus snd_hda_codec_generic snd_hda_intel
[   90.385712]  snd_hda_codec brcmfmac snd_hda_core btusb btrtl snd_hwdep btbcm intel_pch_thermal btintel lpc_ich i2c_i801 brcmutil bluetooth snd_seq cfg80211 snd_seq_device snd_pcm thunderbolt mmc_core bcm5974 rfkill snd_timer mei_me snd mei soundcore shpchp acpi_als kfifo_buf industrialio sbs sbshc tpm_tis spi_pxa2xx_platform tpm apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 hid_apple i2c_algo_bit drm_kms_helper drm video fjes coretemp applesmc input_polldev
[   90.385733] CPU: 1 PID: 1700 Comm: Xorg Tainted: G        W  OE   4.4.8-300.fc23.x86_64 #1
[   90.385734] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   90.385735]  0000000000000286 00000000d873bb2f ffff8802636fbd10 ffffffff813b5f5e
[   90.385737]  0000000000000000 ffffffffa079abf1 ffff8802636fbd48 ffffffff810a4122
[   90.385739]  0000000000000000 ffff8802636fbde8 ffff88025a530b00 0000000000000072
[   90.385742] Call Trace:
[   90.385745]  [<ffffffff813b5f5e>] dump_stack+0x63/0x85
[   90.385747]  [<ffffffff810a4122>] warn_slowpath_common+0x82/0xc0
[   90.385749]  [<ffffffff810a426a>] warn_slowpath_null+0x1a/0x20
[   90.385752]  [<ffffffffa07978bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   90.385763]  [<ffffffffa004c4b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   90.385771]  [<ffffffffa003c5f2>] drm_ioctl+0x152/0x540 [drm]
[   90.385780]  [<ffffffffa004c410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   90.385783]  [<ffffffff813407bc>] ? selinux_file_ioctl+0x10c/0x1c0
[   90.385785]  [<ffffffff81241378>] do_vfs_ioctl+0x298/0x480
[   90.385788]  [<ffffffff81338073>] ? security_file_ioctl+0x43/0x60
[   90.385790]  [<ffffffff812415d9>] SyS_ioctl+0x79/0x90
[   90.385792]  [<ffffffff817a13ae>] entry_SYSCALL_64_fastpath+0x12/0x71
[   90.385794] ---[ end trace 684b75046f045d0e ]---
[   90.385970] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   90.385971] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   90.385977] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   90.385978] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   90.388137] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.388336] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.388725] evdi: [D] evdi_detect:72 Painter is disconnected
[   90.414765] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff8802627b4000 tries to close us
[   90.414768] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   90.440179] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff8802627b5400 tries to close us
[   90.440182] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   90.460487] evdi: [E] evdi_painter_connect:405 Edid length too large
[  121.303722] evdi: [D] evdi_detect:72 Painter is disconnected
[  121.303740] evdi: [D] evdi_detect:72 Painter is disconnected
```
No monitors were detected.

**Comment by displaylink-mlukaszek** [comment]
New evdi release needs an updated DisplayLinkManager - this is the helper application that talks to DisplayLink devices. We are working on releasing this soon. The old version will not work with newer libevdi.

**Comment by displaylink-mlukaszek** [comment]
The new 1.1.62 release is now shipping, it includes evdi fixes that should fix this.

**Comment by wpoely86** [comment]
Unfortunately, it doesn't fix it. On kernel 4.4.9 with xorg-server 1.18:
```
[    6.860687] evdi: module verification failed: signature and/or required key missing - tainting kernel
[    6.862573] evdi: [I] Initialising logging on level 5
[   48.095941] evdi: [D] add_store:195 Increasing device count to 1
[   48.100476] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[   48.104540] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exist!
[   48.104544] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.104549] evdi evdi.0: No connectors reported connected with modes
[   48.104551] [drm] Cannot find any crtc or sizes - going 1024x768
[   48.106075] evdi evdi.0: fb1: evdidrmfb frame buffer device
[   48.106079] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   48.106081] [drm] No driver support for vblank timestamp query.
[   48.106082] [drm] evdi: evdi_stats_init
[   48.106097] [drm] Initialized evdi 1.1.61 20160510 on minor 1
[   48.108274] ------------[ cut here ]------------
[   48.108284] WARNING: CPU: 3 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.108285] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.108320]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.108349] CPU: 3 PID: 1678 Comm: Xorg Tainted: G           OE   4.4.9-300.fc23.x86_64 #1
[   48.108350] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.108352]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.108354]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.108357]  0000000000000000 ffff88024b3efde8 ffff880078ffb500 0000000000000072
[   48.108359] Call Trace:
[   48.108365]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.108368]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.108371]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.108374]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.108390]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.108399]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.108409]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.108413]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.108417]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.108420]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.108422]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.108425]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.108427] ---[ end trace 385ac4d5693ab206 ]---
[   48.129037] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.129123] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.130630] ------------[ cut here ]------------
[   48.130639] WARNING: CPU: 3 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.130640] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.130678]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.130711] CPU: 3 PID: 1678 Comm: Xorg Tainted: G        W  OE   4.4.9-300.fc23.x86_64 #1
[   48.130713] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.130715]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.130718]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.130721]  0000000000000000 ffff88024b3efde8 ffff880235de6900 0000000000000072
[   48.130724] Call Trace:
[   48.130730]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.130734]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.130736]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.130740]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.130756]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.130766]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.130779]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.130784]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.130787]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.130791]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.130793]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.130797]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.130799] ---[ end trace 385ac4d5693ab207 ]---
[   48.130850] ------------[ cut here ]------------
[   48.130856] WARNING: CPU: 3 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.130857] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.130890]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.130917] CPU: 3 PID: 1678 Comm: Xorg Tainted: G        W  OE   4.4.9-300.fc23.x86_64 #1
[   48.130919] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.130920]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.130923]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.130926]  0000000000000000 ffff88024b3efde8 ffff880235de6f00 0000000000000072
[   48.130929] Call Trace:
[   48.130932]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.130935]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.130938]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.130942]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.130956]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.130966]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.130978]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.130981]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.130985]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.130989]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.130992]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.130994]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.130996] ---[ end trace 385ac4d5693ab208 ]---
[   48.131465] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   48.131468] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   48.131495] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   48.131496] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   48.180105] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff88007fd47200 tries to close us
[   48.180108] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   48.187153] usb 1-2.2.3: new high-speed USB device number 7 using xhci_hcd
[   48.212450] evdi: [D] evdi_painter_connect:433 (dev=0) Connected with           (null)
[   48.212456] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.213102] evdi: [D] add_store:195 Increasing device count to 2
[   48.214260] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[   48.214988] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.214992] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   48.221384] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exist!
[   48.221388] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.221391] evdi evdi.1: No connectors reported connected with modes
[   48.221393] [drm] Cannot find any crtc or sizes - going 1024x768
[   48.221546] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.221551] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   48.222545] evdi evdi.1: fb2: evdidrmfb frame buffer device
[   48.222549] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   48.222550] [drm] No driver support for vblank timestamp query.
[   48.222552] [drm] evdi: evdi_stats_init
[   48.222557] [drm] Initialized evdi 1.1.61 20160510 on minor 2
[   48.226600] ------------[ cut here ]------------
[   48.226610] WARNING: CPU: 0 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.226612] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.226657]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.226689] CPU: 0 PID: 1678 Comm: Xorg Tainted: G        W  OE   4.4.9-300.fc23.x86_64 #1
[   48.226691] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.226693]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.226696]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.226699]  0000000000000000 ffff88024b3efde8 ffff8801ea90ed00 0000000000000072
[   48.226702] Call Trace:
[   48.226709]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.226713]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.226715]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.226719]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.226736]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.226746]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.226760]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.226764]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.226768]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.226772]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.226775]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.226778]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.226780] ---[ end trace 385ac4d5693ab209 ]---
[   48.231385] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.231441] evdi: [D] evdi_detect:72 Painter is disconnected
[   48.231746] ------------[ cut here ]------------
[   48.231754] WARNING: CPU: 1 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.231756] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.231795]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.231829] CPU: 1 PID: 1678 Comm: Xorg Tainted: G        W  OE   4.4.9-300.fc23.x86_64 #1
[   48.231831] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.231832]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.231835]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.231838]  0000000000000000 ffff88024b3efde8 ffff8801eaadc400 0000000000000072
[   48.231841] Call Trace:
[   48.231847]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.231851]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.231853]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.231857]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.231874]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.231885]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.231898]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.231904]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.231908]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.231911]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.231914]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.231918]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.231920] ---[ end trace 385ac4d5693ab20a ]---
[   48.231932] ------------[ cut here ]------------
[   48.231936] WARNING: CPU: 1 PID: 1678 at include/drm/drm_gem.h:146 evdi_dumb_create+0xdd/0xf0 [evdi]()
[   48.231938] Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm snd_usbmidi_lib usbnet snd_rawmidi mii rfcomm fuse nf_conntrack_netbios_ns nf_conntrack_broadcast evdi(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_filter ebtable_broute bridge stp llc ebtable_nat ebtables ip6table_raw ip6table_mangle ip6table_security ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_filter ip6_tables iptable_raw iptable_mangle iptable_security iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack bnep snd_hda_codec_cirrus snd_hda_codec_hdmi snd_hda_codec_generic intel_rapl iosf_mbi brcmfmac snd_hda_intel snd_hda_codec x86_pkg_temp_thermal kvm_intel nls_utf8 kvm hfsplus joydev snd_hda_core iTCO_wdt iTCO_vendor_support brcmutil irqbypass
[   48.231969]  cfg80211 crct10dif_pclmul snd_hwdep crc32_pclmul snd_seq snd_seq_device btusb btrtl btbcm btintel crc32c_intel bluetooth snd_pcm mmc_core intel_pch_thermal rfkill i2c_i801 thunderbolt bcm5974 mei_me snd_timer lpc_ich mei shpchp snd soundcore acpi_als sbs kfifo_buf sbshc industrialio tpm_tis tpm spi_pxa2xx_platform apple_bl nfsd auth_rpcgss nfs_acl lockd grace sunrpc i915 i2c_algo_bit drm_kms_helper drm fjes video hid_apple coretemp applesmc input_polldev
[   48.231995] CPU: 1 PID: 1678 Comm: Xorg Tainted: G        W  OE   4.4.9-300.fc23.x86_64 #1
[   48.231997] Hardware name: Apple Inc. MacBookPro12,1/Mac-E43C1C25D4880AD6, BIOS MBP121.88Z.0167.B12.1508182325 08/18/2015
[   48.231998]  0000000000000286 000000007ff0057d ffff88024b3efd10 ffffffff813b62ee
[   48.232001]  0000000000000000 ffffffffa0789bf1 ffff88024b3efd48 ffffffff810a4252
[   48.232004]  0000000000000000 ffff88024b3efde8 ffff880261f0d700 0000000000000072
[   48.232006] Call Trace:
[   48.232010]  [<ffffffff813b62ee>] dump_stack+0x63/0x85
[   48.232013]  [<ffffffff810a4252>] warn_slowpath_common+0x82/0xc0
[   48.232015]  [<ffffffff810a439a>] warn_slowpath_null+0x1a/0x20
[   48.232019]  [<ffffffffa07868bd>] evdi_dumb_create+0xdd/0xf0 [evdi]
[   48.232032]  [<ffffffffa00634b8>] drm_mode_create_dumb_ioctl+0xa8/0xc0 [drm]
[   48.232042]  [<ffffffffa00535f2>] drm_ioctl+0x152/0x540 [drm]
[   48.232052]  [<ffffffffa0063410>] ? drm_mode_page_flip_ioctl+0x370/0x370 [drm]
[   48.232056]  [<ffffffff81340adc>] ? selinux_file_ioctl+0x10c/0x1c0
[   48.232059]  [<ffffffff81241648>] do_vfs_ioctl+0x298/0x480
[   48.232062]  [<ffffffff81338393>] ? security_file_ioctl+0x43/0x60
[   48.232065]  [<ffffffff812418a9>] SyS_ioctl+0x79/0x90
[   48.232067]  [<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[   48.232069] ---[ end trace 385ac4d5693ab20b ]---
[   48.232245] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   48.232248] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   48.232253] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=0) Notifying crtc state: 3
[   48.232255] evdi: [W] evdi_painter_send_crtc_state:253 Painter is not connected!
[   48.235590] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.235594] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   48.236210] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.236214] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   48.273259] usb 1-2.2.3: New USB device found, idVendor=0424, idProduct=2514
[   48.273266] usb 1-2.2.3: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[   48.275763] hub 1-2.2.3:1.0: USB hub found
[   48.275911] hub 1-2.2.3:1.0: 4 ports detected
[   48.279762] evdi: [W] evdi_painter_disconnect:462 (dev=1) An unknown connection to ffff880262939a00 tries to close us
[   48.279765] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   48.307799] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff880262939a00 tries to close us
[   48.307802] evdi: [W] evdi_painter_disconnect:463  - ignoring
[   48.336197] evdi: [D] evdi_painter_connect:433 (dev=0) Connected with           (null)
[   48.336202] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   48.415553] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   48.415558] evdi: [D] evdi_painter_get_edid_copy:186 (dev=2) 00 ff ff
[   48.416188] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.416193] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   48.418921] evdi: [D] evdi_painter_mode_changed_notify:376 (dev=1) Notifying mode changed: 1920x1080@60; bpp 32; 
[   48.418925] evdi: [D] evdi_painter_mode_changed_notify:377 pixel format 875713112
[   48.418933] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=1) Notifying crtc state: 0
[   48.861336] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   48.861340] evdi: [D] evdi_painter_get_edid_copy:186 (dev=2) 00 ff ff
[   48.862409] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   48.862413] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   56.201625] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   56.201630] evdi: [D] evdi_painter_get_edid_copy:186 (dev=2) 00 ff ff
[   56.202546] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   56.202550] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   60.891905] evdi: [D] evdi_painter_mode_changed_notify:376 (dev=2) Notifying mode changed: 1920x1080@60; bpp 32; 
[   60.891908] evdi: [D] evdi_painter_mode_changed_notify:377 pixel format 875713112
[   60.891916] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=2) Notifying crtc state: 0
[   61.075806] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   61.075812] evdi: [D] evdi_painter_get_edid_copy:186 (dev=2) 00 ff ff
[   61.083783] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   61.083789] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   61.483069] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   61.483915] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   61.485046] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   61.568456] evdi: [D] evdi_detect:69 (dev=2) Painter is connected
[   61.568461] evdi: [D] evdi_painter_get_edid_copy:186 (dev=2) 00 ff ff
[   61.568747] evdi: [D] evdi_detect:69 (dev=1) Painter is connected
[   61.568750] evdi: [D] evdi_painter_get_edid_copy:186 (dev=1) 00 ff ff
[   62.149524] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   62.149860] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   62.150332] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   69.691424] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x113, supported mask 0x7400003f
[   73.682534] evdi: [W] evdi_painter_mode_changed_notify:384 (dev=1) Change mode duplicated - ignoring
[   73.682548] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=1) Notifying crtc state: 0
[   73.689980] evdi: [W] evdi_painter_mode_changed_notify:384 (dev=2) Change mode duplicated - ignoring
[   73.689985] evdi: [D] evdi_painter_crtc_state_notify:359 (dev=2) Notifying crtc state: 0
```
